#!/bin/bash

GREEN="\e[32m"
BOLD="\e[1m"
PADDING="\n"
RESET="\e[0m"

echo -e "${GREEN}${BOLD}${PADDING}===> Enter your Linux username and press Enter to continue...${PADDING}${RESET}"
read user

echo -e "${GREEN}${BOLD}${PADDING}===> Installing packages...${PADDING}${RESET}"

apt-get update -qq

PACKAGES=(autoconf libev4 libev-dev libstartup-notification-1.0 gir1.2-webkit-3.0 wkhtmltopdf
            python-pip python3 python3-pip python3-markdown python-gtk2 i3status i3lock
            network-manager network-manager-gnome curl vim feh thunar meld git
            dmenu terminator chromium-browser firefox alsa-utils alsa-oss openssh-server openssh-client
            keychain xbacklight xfonts-terminus console-terminus zsh)

for package in "${PACKAGES[@]}"
do
    echo -e "${GREEN}${BOLD}${PADDING}===> Installing ${package}...${PADDING}${RESET}"
    apt-get install -y $package
done

# echo -e "${GREEN}${BOLD}${PADDING}===> Installing i3-gaps...${PADDING}${RESET}"

# git clone https://github.com/Airblader/i3 i3-gaps

# cd i3-gaps && autoreconf --force --install && rm -rf build &&
# mkdir -p build && cd build &&
# ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers &&
# make && make install && cd && rm -rf i3-gaps

echo -e "${GREEN}${BOLD}${PADDING}===> Installing remarkable...${PADDING}${RESET}"

curl https://remarkableapp.github.io/files/remarkable_1.87_all.deb > remarkable.deb
dpkg -i remarkable.deb
rm remarkable.deb

echo -e "${GREEN}${BOLD}${PADDING}===> Setting zsh as the default shell for ${user}...${PADDING}${RESET}"

usermod -s $(which zsh) ${user}

echo -e "${GREEN}${BOLD}${PADDING}===> Installing oh-my-zsh...${PADDING}${RESET}"

git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
chown -R ${user}

echo -e "${GREEN}${BOLD}${PADDING}===> Installing pip packages...${PADDING}${RESET}"

pip install virtualenv virtualenvwrapper escrotum
pip3 install py3status pytz tzlocal

echo -e "${GREEN}${BOLD}${PADDING}===> Installing powerline fonts...${PADDING}${RESET}"

git clone https://github.com/powerline/fonts.git --depth=1 &&
    cd fonts && ./install.sh && cd .. && rm -rf fonts

echo -e "${GREEN}${BOLD}${PADDING}===> Installing fzf fuzzy finder...${PADDING}${RESET}"

git clone --depth=1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

echo -e "${GREEN}${BOLD}${PADDING}===> Backing up possible existing configs...${PADDING}${RESET}"

mv -b ~/.dmrc ~/.dmrc_bk
mv -b ~/.i3 ~/.i3_bk
mv -b ~/.zshrc ~/.zshrc_bk
mv -b ~/.vimrc ~/.vimrc_bk
mv -b ~/.vim ~/.vim_bk
mv -b ~/.config/terminator ~/.config/terminator_bk

echo -e "${GREEN}${BOLD}${PADDING}===> Creating symlinks to configs in BootStraPC...${PADDING}${RESET}"

ln -sf ~/.bootstrapc/dotfiles/dmrc ~/.dmrc
ln -sf ~/.bootstrapc/dotfiles/i3 ~/.i3
ln -sf ~/.bootstrapc/dotfiles/zshrc ~/.zshrc
ln -sf ~/.bootstrapc/dotfiles/zsh_custom ~/.zsh_custom
ln -sf ~/.bootstrapc/dotfiles/vimrc ~/.vimrc
ln -sf ~/.bootstrapc/dotfiles/vim ~/.vim
ln -sf ~/.bootstrapc/dotfiles/terminator ~/.config/terminator

echo -e "${GREEN}${BOLD}${PADDING}===> Creating directory for screenshots...${PADDING}${RESET}"

mkdir -p ~/Pictures/screenshots

echo -e "${GREEN}${BOLD}${PADDING}===> Installing vim plugins...${PADDING}${RESET}"

vim -c VundleUpdate -c quitall

echo -e "${GREEN}${BOLD}${PADDING}===> Bootstrap finished! Remember to restart!${PADDING}${RESET}"
